CISOfy/lynis

- include/tests_boot_services
The default rescue.service unit file was updated
in the systemd repo on Jan 23, 2015
to allow for sulogin location variability.
> Update check for sulogin under systemd.

- include/tests_filesystems
Prevent the locate test from running spuriously when locate is not present.
> Pass information about locate prereqs to Register.

- include/tests_squid
The grep statement needs to be modified to prevent tagging port values that contains a value in `SQUID_DAEMON_UNSAFE_PORTS_LIST` but aren't actually equal to the listed port value
> Fix false positive matches with unsafe ports on SQD-3624

- include/tests_storage
By default, grep uses basic regular expressions (BRE). BRE needs '(', '|', and ')' escaped.
> Fix STRG-1840 (Check for disabled USB storage)

- include/tests_containers
When running the Container tests;
If the Docker binary is present but when the Docker daemon is not running, or DOCKER_HOST unset, the Container tests logs two error-messages, as shown below: 
```
[+] Containers
------------------------------------
- Docker info output (warnings)                       [ NONE ]
- Containers
- Total containers                                    [ UNKNOWN ]
time="2015-07-24T23:30:13+02:00" level=fatal msg="Cannot connect to the Docker daemon. Is 'docker -d' running on this host?"
- Running containers                                  [        0 ]
./include/tests_containers: line 145: [: -gt: unary operator expected
[+] Custom Tests
------------------------------------
- Running custom tests...                                   [ NONE ]
```
With this pull …
> Comparison error when Docker is present, but the daemon is not running (or unset).

- include/functions
Lynis contains a check to determine whether the server is virtualized or not. On a bare metal machine, lshw can take over 10 seconds. Especially if you run `lynis update info` to check if you have the latest Lynis installed, this is undesirable. 
Much faster than `lshw` would be `dmidecode -s system-product-name`, but I'm not sure if the output could be 100% reliable be interpreted. If the system has facter installed (part of Puppet), then this will be a much more reliable and faster way to check virtualization.
> More reliable and often faster check to determine virtualization.

- CONTRIBUTORS
- lynis
After finding that the MYHOMEDIR is empty, the base version of lynis sets HOMEDIR to /tmp (line 318). This appears to be a typo since $HOMEDIR is not referenced anywhere and the empty $MYHOMEDIR is used in line 319. This has the undesirable effect of writing a PIDFILE in the root directory.
Fixing this typo is great, but it creates a possible symlink attack. Line 332 writes the lynis process ID to the pidfile. If an attacker creates a symlink at /tmp/lynis.pid on a system without an immutable /tmp directory (and without a /var/run directory), executing lynis will clobber the target of that symlink, overwriting file contents with the process ID of the running lynis process.
This is a corner case. Nonetheless, I've largely mitigated this vulnerability by removing PIDFILE immediately before …
> Small PIDfile fixes

- include/tests_authentication
- include/tests_homedirs
- include/tests_logging
- include/tests_nameservices
- include/tests_networking
- include/tests_ports_packages
- include/tests_webservers
Combine "sort | uniq" into "sort -u" to reduce the number of processes used for running Lynis.
The busybox version of sort also supports the -u option.
> Combine "sort | uniq" to "sort -u"

- extras/build-lynis.sh
- include/data_upload
- include/functions
- include/osdetection
- include/profiles
- include/report
- include/tests_authentication
- include/tests_boot_services
- include/tests_databases
- include/tests_file_permissions
- include/tests_insecure_services
- include/tests_kernel
- include/tests_logging
- include/tests_memory_processes
- include/tests_nameservices
- include/tests_php
- include/tests_shells
- include/tests_snmp
- include/tests_squid
- include/tests_ssh
- include/tests_storage_nfs
- include/tests_time
- include/tests_webservers
Less processes are created during the Lynis run.
Detection of duplicate entries in /etc/hosts is now more robust.
On CentOS7 the SERVICE_MANAGER is detected correctly.
> Optimized use of cat, grep and awk.

- include/tests_logging
LOGG-2154: syslog-ng config file has a different syntax
> Remote syslog server not detected for syslog-ng

- include/tests_authentication
- include/tests_nameservices
AUTH-9208: OpenBSD has /etc/master.passwd of course
AUTH-9234: OpenBSD real user ids run from 1000-60000 without 32767 by default; enable this test for non-Linux in the first place
> Authentication fixes for OpenBSD

- include/tests_ssh
Belongs in ssh_config instead.  Ref issue #120
> Removed ServerAliveInterval

- include/functions
Helps resolve #128.
I thought doing it this way would minimise the impact on anyone who already parses the log file somehow.
> Make AddHP identify non-optimal HP in logfile entries

- include/tests_authentication
Added pwquality (default in some Ubuntu variants) to accepted password-quality modules - addresses issue #118.
Restructured tests so that full points (3/3) are granted if any of these libraries are installed (particularly because passwdqc and cracklib are incompatible).
> AUTH-9262 - restructure + pwquality

- include/tests_php
On my EL6 systems PHP uses an ini directory of /etc/php.d, added this to the php test.
> Added ini dir of EL6

- include/tests_logging
One of the features in grsecurity also prevents Fail2Ban from creating a temp file under /var/tmp.  I've been unable to pinpoint the line in fail2ban which causes the issue, but have confirmed it's related to grsecurity.
Note: disabling the PaX MPROTECT function on /usr/bin/python will also resolve this issue, but it's better to keep MPROTECT on.
> Hide fail2ban open+deleted file warning, when grsec is installed

- include/tests_kernel
KRNL-5788 had some issues with grsecurity.  Specifically:
- /vmlinuz missing caused the test to fail.  #175 
- Threw a misleading error message re apt-cache.  #176 
This patch:
- Responds appropriately to missing /vmlinuz, but only when grsecurity is installed
- If /vmlinuz is missing, and grsec is NOT installed, throws a ReportException
- Suggests the auditor manually check to confirm a recent kernel+grsec is running
@mboelen - Have tested on **one system only**.  I'd appreciate further testing before merging.  :-)
> Update KRNL-5788 for grsecurity

- include/tests_boot_services
On CentOS 7, the file /etc/rc.local is a symlink to /etc/rc.d/rc.local.
In that case, the script raises an error. The symlink is world readable, which is not the case of the real file.
```
File: ‘/etc/rc.local’ -> ‘rc.d/rc.local’
Size: 13              Blocks: 0          IO Block: 4096   symbolic link
Device: fd01h/64769d    Inode: 88540       Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:etc_t:s0
Access: 2016-05-02 11:20:18.794261132 +0200
Modify: 2016-04-01 11:56:54.061649752 +0200
Change: 2016-04-01 11:56:54.061649752 +0200
Birth: -
```
> Check if file is symlink or not

- include/tests_logging
- grep for whole words to ignore
- logging what exactly keeps a file open can be very helpful
> - [LOGG-2190]:  Running lynis from /etc/cron.daily makes some programs delete in-use files

- include/tests_ssh
See Issue #197.  
References:
- https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/424371/comments/11
- https://unix.stackexchange.com/questions/56941/what-is-the-point-of-sshd-usedns-option
- https://security.googleblog.com/2016/02/cve-2015-7547-glibc-getaddrinfo-stack.html
> UseDNS = No is a safer configuration

- include/tests_ports_packages
Improve non-interactive behavior of zypper.
* Always run with -n (non-interactive) to prevent questions that block execution of lynis
* for PKGS-7328 only list packages
> improve non-interactive use of zypper

- default.prf
from https://lwn.net/Articles/420403/:
>   The %pK format specifier is designed to hide exposed kernel
>   pointers, specifically via /proc interfaces.  Exposing these
>   pointers provides an easy target for kernel write vulnerabilities,
>   since they reveal the locations of writable structures containing
>   easily triggerable function pointers.  The behavior of %pK depends
>   on the kptr_restrict sysctl. […] If kptr_restrict is set to 2,
>   kernel pointers using %pK are printed as 0's regardless of
>   privileges.
> expect value of sysctl:kernel.kptr_restrict to be 2

- include/tests_filesystems
[removed links]
Some chapters ask to remove the support of some filesystems : cramfs hfs hfsplus squashfs udf freevxfs jffs2
Tested on Red Hat 7.2 and CentOS 7.2
> Remove the support of some filesystems

- include/tests_filesystems
This mount option (for Linux >= 3.3) hides users' sensitive files in /proc from other users.
See `man proc` for details.
> check if /proc mounted with hidepid=(1|2)

- include/functions
After changes in 9aa5736 the test names are different. This results in something like BOOT-5122 = boot-5122 and skipped test aren't skipped anymore. Changed from lower to upper, to match display commit.
> fix: Test names are different

- include/functions
- lynis
Display function uses wc to calc the number of spaces between label and result; wc requires LANG value to deal with multi-bytes characters, e.g. accentuated ones in french with utf-8.
But atm LANG is unset inside include/consts. Then 'wc -m' returns the number of bytes, not the number of unicode code points, i.e. "characters". On the concerned raws, the result is misaligned (too closed of the label).
> i18n: wrong indentation of result column

- include/functions
"Adds a system to a group, which can be used for categorizing" should belong to 
AddSystemGroup but not CheckFilePermissions
> Fix description of CheckFilePermissions

- include/tests_ports_packages
Issue #245 
yum.conf allows an arbitrary number of spaces to surround the equals assignment.
> fix yum gpgenabled check to allow spaces around =

- include/functions
These function made mistake in centos 6.8 virtual machine. Only dmicecode work
on these environment and it return Openstack Nova. A openstack case is needed
in codes that check $SHORT codes.
> Make IsVirtualMachine detect centos6.8 on openstack

- include/tests_filesystems
The result of mount command returns like
/proc on /proc type proc (rw,hidepid=2)
Witch means the regular expression should be '^/proc' not '^proc' or you can grep nothing. :P
> Fix FILE-6344 bug

- include/tests_filesystems
GlusterFS mounts use fuse and are nodev and nosuid by default. Also nodev and nosuid are invalid mount options. So ignore GlusterFS mount points in check FILE-6374.
> Ignore GlusterFS for nodev and nosuid checks

- include/tests_networking
In test **NETW-3032** check for [_ArpON_](https://en.wikipedia.org/wiki/ArpON) as ARP monitoring software. 
Tested with:
- Ubuntu 16.04
- arpon 2.7.2
This fixes #266 issue.
> Check for arpon as ARP monitoring software

- include/tests_webservers
When a Apache config directive is in use, it has whitespace(s) or nothing at all prepended. Assuming that it always has a space before it doesn't have to match.
I thought I'd submitted this PR already, but it seemed not to have happened, strangely enough ...
> Fix sed syntax for ServerAlias removal

- include/tests_time
As jails get their time from the host and do not have their own clocks, it's not useful to run a time synchronization program from within the jail.
> Skip NTP checks from within a FreeBSD jail

- include/tests_tooling
Rudder (http://www.rudder-project.org) is a config management tool with automatic reporting / dynamic policy adjustment.
The "dynamic" bit happens using FusionInventory.
The config management part uses CFEngine under the hood.
I don't know if hw/os inventory tools also matter in the Lynis report, if yes, I can look into that too.
This patch extends the path searched to detect a running CFEngine agent (and fileserver daemon)
Since the agent is the same, this should immediately detect it.
> Add support for Rudder configuration management

- CHANGELOG.md
- include/tests_malware
Added support to detect if Bitdefender Antivirus for Mac is running.
> [MALW-3280] Bitdefender AV Support (macOS)

- include/tests_file_integrity
Warning given if AIDE is detected but no configuration file found.
Without configuration file AIDE will not work.
> [FINT-4315] Warning for missing AIDE conf file

- include/tests_boot_services
Test will display result in red if no boot loader password set and if
server or workstation role was set. Cosmetic change for log text, one
instead of two log texts.
Test displays result in yellow if using personal machine role as
suggestion for typical users.
> [BOOT-5139] LILO suggestions changed for new machine-roles

- include/tests_hardening
Results for malware scanner will show  different color for “personal”
machine-roles (in yellow) rather than the other roles (in red).
Added for leniency towards typical personal PC users for not having
malware scanner (should be a suggestion).
Also included log text result if no scanner found, regardless of
machine-role.
> [HRDN-7230] Result colors changed, added result log text

- include/tests_authentication
The LogText Output for test 9208 was worded oddly. 
"Non unique UIDs can riskful for..." has been changed to:
"Non unique UIDs can be a risk for..."
- and - 
Test 9234, specifically finding the Real User info, originally using `/etc/passwd`.  macOS does NOT use `/etc/passwd` to store the user info, but rather the default system users. macOS uses `opendirectoryd` for the backend user service. Thus, the program `dscacheutil` is whats recommended to query the various items in opendirectoryd. I left comments in the test section with the basic commands you can use as reference for building out the correct FIND commands.
> Updates to include/tests_authentication

- include/parameters
The Dockerfile audit command is currently broken since it tries to pull too many parameters.
> Fix Dockerfile audit

- CHANGELOG.md
- include/tests_authentication
Actually : 
```
Test: Checking umask value in /etc/init.d/functions
Result: found umask 0027, which could be improved
```
Expected : 
```
Test: Checking umask value in /etc/init.d/functions
Result: umask 0027 is considered a properly hardened value
```
> umask can be 0027 or 0077

- include/tests_authentication
This way, accounts that have ":!!:" in shadow and have an entry in
"Password expires" field don't get flagged with "Result: password of
user XYZ has been expired" by AUTH-9288.
Fixes #362
> Fix regex to disregard locked accounts

- include/tests_php
It wasn't finding my PHP config located at `/etc/php/php.ini`, added that path and some variations.
> Add Additional php.ini Paths

- include/tests_firewalls
This should notify the one who make audits that CSF is in testing mode as sometimes you may forget to  disable it on a production environment which leads to flushing the firewall every N seconds. What do you think ?
> Add a check for csf testing mode

- default.prf
Preventing an unprivileged user from viewing the kernel log buffer may be an important part of general hardening of the system.   This can help prevent an attacker from gathering debugging information that might be valuable during exploitation.
It's a simple 1 line addition to default.prf, what do you think?
> Added kernel.dmesg_restrict to sysctl checks.

- include/helper_show
Hi,
This PR is to fix changelog path on Fedora/RHEL systems, since the package name is lower case.
**Before the patch:**
```
[athmane@devel2 ~]$ sudo lynis show changelog
Error: Could not find the changelog file (searched in /usr/share/doc/Lynis /usr/share/doc/Lynis-2.5.1 .)
```
**After the patch:**
```
[athmane@devel2 ~]$ sudo lynis show changelog
Lynis 2.5.1 (2017-05-31)
Changes:
- Hebrew translation by Dolev Farhi
- Improved detection of SSL certificate files
- Minor changes to improve logging and results
Tests:
--------
* BOOT-5104 - Added support for macOS
* FIRE-4524 - Determine if CSF is in testing mode
* HTTP-6716 - Improved log message
---------------------------------------------------------------------------------
```
> Add lowercase path for changelog search (eg: Fedora/EPEL pkg)

- CONTRIBUTORS.md
There is a broken URL within the `CONTRIBUTORS.md` file.
> Fix URL in CONTRIBUTORS.md

- include/tests_webservers
Further to https://github.com/CISOfy/lynis/issues/415
The Apache modules path on DirectAdmin based servers that compile Apache via custombuild is `/usr/lib/apache`. This is currently not recognised by lynis, only `/usr/lib/apache2` is searched currently.
> Add /usr/lib/apache module search path for DirectAdmin

- include/tests_php
Lynis does not find php.ini files when executed under Ubuntu 16.04LTS. Added the php.ini file locations for ubuntu 16.04LTS to tests.php.
> Added php.ini locations for Ubuntu 16.04LTS

- include/tests_php
For some reason, the variable PHPVERSION is reset at the beginning of tests_php file. So, the tests that use it cannot work (e.g. PHP-2368).
> Do not unset PHPVERSION after detect it

- include/tests_ports_packages
Debsums is supported on Debian and other systems as per GitHub issue #446. 
Undo commit d1969001c6df84ea58c7913140a7a03f6b2486a1 (which was requested in #413).
> Do not limit debsums to Debian systems

- include/tests_networking
This specifically makes it so that when `/etc/resolv.conf` has one or more nameservers matching `127.0.[0-1].1` it should not warn as it is using local resolvers.
We are simply using `grep -c "127.0.[0-1].1" /etc/resolv.conf` to determine this.
> [NETW-2705] This is related to #437 and resolvconf but is split up.

- include/helper_audit_dockerfile
The result of the signing keys check is saved under KEYS_USED variable,
but SSL_USED was used to present the result to the end user.
> Fix displayed result for signing keys check

- include/tests_php
My PHP FPM setup is currently not detected by Lynis. I use DirectAdmin and the php.ini for php-fpm via Custombuild 2.0 is installed to the following location:
```/usr/local/php70/lib/php.ini```
The `php70` would vary based on the PHP base version.
https://help.directadmin.com/item.php?id=301
It looks like the default PHP CLI path is already searched, but the CGI and PHP-FPM implementations would not be detected. I've added these paths to the `PHPINILOCS` variable.
> Add additional DirectAdmin paths for php.ini

- include/binaries
sorting BIN_PATHS before traversing each one will produce results that are repeatable.  This isn't a big deal but it is nice to have when comparing logs to establish trends.
> sort BIN_PATHS before process

- include/consts
- include/tests_webservers
Non printable ESC character is required to obtain terminal escape
sequence i.e. for changing output color.
Such sequences (especially ESC character) were replaced by command
substitution producing exactly same result (variable value), but using
only "safe" characters.
Use of printf and especialy '\033' or '\0ddd' sequences is described
here:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/printf.html#tag_20_94_13
Use of $(command) or command substitution is described here:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_03
Verbatim TAB characters were replaced with \t escape sequence as
described to avoid problems with editors silently replacing them or
developer accidentialy messing up the regex.
> remove non printable characters from code

- include/functions
Add a check for process VBoxService , observed to be running in a vagrant VM that uses VirtualBox 5.1.22.
> VBoxService running is another VirtualBox clue

- include/tests_boot_services
The SEARCHED flag seems it should be set for these tests.
> touchup BOOT_LOADER_SEARCHED setting for BOOT-5106 and BOOT-5108

- include/tests_mail_messaging
Checks for exim only if exim4 is not running.
exim4 is known to be Ubuntu 16's exim...
> also find exim4 in MAIL-8802

- include/tests_networking
- dhcpd is a server; the client is dhcpcd
- While here, add udhcpc to the list of recognised DHCP clients
> Fix/amend DHCP client detection

- include/tests_ssh
This configuration item is still in play on modern SSH (Ubuntu,RHEL 7).  it may be on by default, but in my opinion, it should still be tested.
It was active in 2.5.1, but by the time 2.5.7 came around, it was missing.  This patch restores the value.
> restore UsePrivilegeSeparation to list of ssh daemon checks

- db/tests.db
- include/tests_accounting
- include/tests_firewalls
- include/tests_nameservices
- include/tests_printers_spools
- plugins/plugin_systemd_phase1
There are several tests that have minor differences between the testname in the comment, the Register statement, and db/tests.db. 
There is one duplicate db record.
There are nine tests that have no db record.  New db records are created using the Register arguments for testname, os, and description.  The Group is formed from the filename that holds the test.  The CORE-1000 is given to the system_integrity group as it seems the best fit.
The db records are sorted.  No FINT,PROC lines were changed, except for their position.
Given that the USB tests are migrating from STRG, these changes should be scrutinized carefully.
> Pin db sync

- include/tests_boot_services
- include/tests_firewalls
Creating new pull request for this. Previous one got messed up and could not find a good workaround.
Commit solves Null Byte Bash Warning as reported on Issue #515 . Similar error was present on test_boot_services, solved here as well.
> Solved null byte bash warning

- include/tests_php
I use the Remi repo for PHP and components on a server. Lynis currently doesn't detect PHP being installed when using the Remi repo as the paths are quite bespoke:
```
/etc/opt/remi/php56/php.ini
/etc/opt/remi/php70/php.ini
/etc/opt/remi/php71/php.ini
/etc/opt/remi/php72/php.ini
```
This should cover the locations for PHP 5.6 and the PHP 7 series.
https://rpms.remirepo.net/
> Add remi repo php.ini paths to tests_php

- lynis
==========================
Changed words to match sentence tense. 
==========================
Removed reference to depracated "wait_for_keypress", replaced with WaitForKeyPress, Ln 351. per https://github.com/CISOfy/lynis/blob/master/include/functions
==========================
Contribution by Justin McAfee  (me [at] justinmcafee [dot] com)
> Updated Sentence tense, replaced deprecated wait_for_keypress.

- include/tests_ssh
Suggesting `Compression (YES --> (DELAYED|NO))` is not necessary since delayed is `a legacy synonym for yes` according to SSHD_CONFIG(5).
> delayed is a legacy synonym

- include/tests_time
Hi Michael,
on RedHat if the step-tickers file exists even it it's empty, the ntpdate start script uses the servers listed in ntp.conf for the initial time synchronization.
Regards,
Carsten
> [TIME-3160] Extend check for step-tickers file for RedHat

- include/tests_ssh
Seems like in the patch there was an extra 'ssh' added in the command line, which is breaking the ssh tests.  Removing the ssh keyword... -T -C ... fixes the problem.
> Updated tests_ssh, removed extra ssh in the test 

- include/tests_networking
Querying a nameserver with the same nameserver might result in a failure even if DNS is working.
```
Testing bionic @127.0.0.53:
OK
Testing www.google.com @127.0.0.53:
OK
Testing 127.0.0.53 @127.0.0.53:
;; connection timed out; no servers could be reached
FAIL
Testing bionic @1.1.1.1:
;; connection timed out; no servers could be reached
FAIL
Testing www.google.com @1.1.1.1:
;; connection timed out; no servers could be reached
FAIL
Testing 1.1.1.1 @1.1.1.1:
;; connection timed out; no servers could be reached
FAIL
```
```
#!/bin/bash
while read -r d; do
echo "Testing $(hostname -f) @$d:"
if dig +noall +time=3 +retry=0 @"$d" "$(hostname -f)"; then
echo "OK"
else
echo "FAIL"
fi
echo "Testing www.google.com @$d:"
if dig +noall +time=3 +retry=0 @"$d" "www.google.com"; then
echo "OK"
else
echo …
```
> query DNS with FQDN

- include/tests_shells
In case when umask is checked in multiple files and in some of the files except the last one a weak umask is found, the tool reports weak mask for the rest of the files. In the example bellow, the weak umask is only in /etc/csh.cshrc. However, the check /etc/profile is reported weak as well.
Expected:
Checking default umask values
Checking default umask in /etc/bashrc [ OK ]
Checking default umask in /etc/csh.cshrc [ WEAK ]
Checking default umask in /etc/profile [ OK ]
Actual:
Checking default umask values
Checking default umask in /etc/bashrc [ OK ]
Chhhhecking default umask in /etc/csh.cshrc [ WEAK ]
Chhhhecking default umask in /etc/profile [ WEAK ]
> Fix for umask check in case of multiple files

- include/tests_webservers
As mentioned in issue #561, the default installation of Apache 2.4 from the ports tree on FreeBSD goes to /..../apache24 folders.
This pull-request contains the patch for this.
Tested on FreeBSD 11.2 and 10.4
> added path information Apache 2.4 on FreeBSD

- CHANGELOG.md
- include/osdetection
openSUSE uses the os-release file too
I'm not sure what you want to have in OS_NAME vs LINUX_VERSION
> fix opensuse os detection with os-release

- include/functions
got this error on debian auditing a docker file when testing an ubuntu Dockerfile when lynis try to find KEY_USED
> avoid “can't shift that many” error

- CHANGELOG.md
- include/osdetection
Strip the double quotes from OS_ID too, currently it's only done for all the other fields.
> osdetection: ignore quotes in OS_ID

- include/binaries
Busybox's wget does't provide the -V parameter to get the version, so
redirect stderr to /dev/null to hide the printed error message
> Fix printed error when wget comes from busybox

- lynis
Issue is present on busybox ash shell without "command" builtin. Fix
issue by redirecting errors to /dev/null
> Fix error printed to screen when run from shell without "command"

- include/tests_authentication
First commit adds permissions checks for files in the configuration drop-in directory (eg. /etc/sudoers.d) if it exists and closes #600 .
Second commit adds permissions checks for the drop-in directory if it exists. Previously only files were checked.
Third commit adds file & directory ownership checks to ensure all sudo configuration files/folders are owned by UID=0 and GID=0.
Also includes minor changes to phrasing and changing all references of 'ls' to 'LSBINARY'.
This has been tested on Linux (Archlinux). Tests included checking (and finding) bad drop-in directory permissions and bad permissions/ownership of files within the drop-in directory.
Needs testing on non-Linux hosts, specifically *BSDs which I understand can have multiple accounts with a UID of 0.
> [AUTH-9252] Sudo configuration file/folder check improvements

- include/tests_firewalls
This test was previously measuring the number of bytes (wc -c)
in the exported JSON which is likely not what was intended and
will lead to false positives anytime the number of output bytes 
exceeds 16.
The export feature is [poorly documented](https://bugzilla.netfilter.org/show_bug.cgi?id=1279) and requires the jansson
package on the target system to export as JSON - which may not
always be the case. 
Lastly, 16 is an arbitrary and uncessarily high number. A simple
workstation firewall can have only [3 rules](https://wiki.nftables.org/wiki-nftables/index.php/Simple_ruleset_for_a_workstation) and be effective.
This commit makes use of 'nft list ruleset' instead of the export
command, strips out blank lines as well as table & chain headers
before measuring the number of lines in the …
> [FIRE-4540] Modify test to better measure rules

- db/tests.db
- include/binaries
- include/tests_authentication
- include/tests_boot_services
- include/tests_hardening
- include/tests_php
- doas is OpenBSD sudo alternative
- OpenBSD uses init and /etc/rc, /etc/rc.d, thus let's call its service manager bsdrc not to see UNKNOWN
- OpenBSD uses rcctl for start/enable daemons (well it lists also non-daemons thus filtered out via grep)
- check OpenBSD rc scripts and configs for not being world readable
- OpenBSD uses clang and gcc as compiler, both present via cc and clang (amd64) and gcc for GNU cc
- php ini and configuration on OpenBSD tunning
> better OpenBSD support

- include/tests_ports_packages
Currently the check for the security archive in Debian/Ubuntu fails, if
the archive is not hosted on security.{debian,ubuntu}.org and the URL
does have trailing slash, such as this:
deb http://deb.debian.org/debian-security/ stretch/updates main
Change the regular expression to allow for a trailing slash in the URL
when filtering the package sources lists.
Fixes #648
Signed-off-by: Timo Sigurdsson <public_timo.s@silentcreek.de>
> [PKGS-7388] Fix false positive warning on missing security archive

- include/tests_kernel
Not all architectures use a /vmlinuz symlink in Debian. For instance,
armhf systems may only provide a symlink in /boot/vmlinuz. Fall back to
testing /boot/vmlinuz if /vmlinuz is not found.
Fixes #649
Signed-off-by: Timo Sigurdsson <public_timo.s@silentcreek.de>
> [KRNL-5788] Fix false positive warning on missing /vmlinuz

- include/binaries
- include/tests_boot_services
Adds a test to detect systemd-boot. The 'bootctl' binary is also
added as this is the utility used to inspect the systemd-boot
configuration.
This test is only executed if systemd is installed, the bootctl
utility exists and the system is booted in UEFI mode.
> [BOOT-5117] Add systemd-boot bootloader detection

- include/tests_boot_services
The first commit fixes a corner case where _systemd_ service names contain multiple periods and were getting truncated after the first one. Using '-F.service' as the _awk_ filter instead of '-F.' ensures the entire service name up to '.service' is captured. Grepping the source tree didn't turn up any further instances of this.
The 2nd commit simplifies the service filtering to use _systemctl_ switches instead of an additional pipe to _awk_.
> [BOOT 5177] Simplify service filter & support multiple periods in names

- lynis
Quote both "${WORKDIR}/include" and "${WORKDIR}/db" directory existence check in if-statements to avoid "Fatal error: can't find directory" in case of a space-character in the ${WORKDIR} path.
> Quote WORKDIR directory existence in lynis

- db/software-eol.db
CentOS 5 and 6 is named `CentOS release`, not `CentOS Linux release`.
> update CentOS releases in software-eol.db

- include/tests_boot_services
At least Slackware Linux uses this. Even though it's compatible with SysV init scripts, it's still technically BSD-style init.
I wasn't sure whether to name it `bsdrc` or `bsdrc.d`, but there's no monolithic `/etc/rc` script I think the `rc.d` is more appropriate. Also for instance [this article](https://www.freebsd.org/doc/en/articles/rc-scripting/article.html) uses `rc.d` name for it.
> Detect BSD-style (rc.d) init in Linux systems

- include/helper_show
Since version 2.6.6 CHANGELOG.md has markdown formatting. This breaks the show changelog command.
This is a workaound to "fix" the issue without changing all the versions strings in CHANGELOG.md
> Prepend sed to discard '## ' in CHANGELOG.md

- include/tests_mail_messaging
A few more tests to consider for Exim4 in tests_mail_messaging:
1.  Display where certificates are installed (Default or Custom)
2.  Show state of "Try Verify Hosts" option
3.  Show state of "Verify Hosts" option
The last two options may seem slightly confusing but while they have confusing labels they enable different functions.  
When "Try Verify Hosts" is enabled, a system will attempt to verify a hosts certificate but will not close the connection if the verification fails.  This is an appropriate setting for an 'Internet Host' configuration for Exim.
When "Verify Hosts" is enabled, the system attempts to verify a host certificate and will close the connection if verification fails.  This is often an appropriate setting for 'Satellite' or 'Smarthost' configurations.  
If 'Verify …
> Added certificate tests for Exim

- include/tests_homedirs
Define 'git' instead of 'git-shell'.
> Fix typos from the fixes for #743

- include/binaries
- include/tests_crypto
There are several challenges with the existing method of using
/etc/crypttab:
1)encrypted rootfs partitions are not typically listed in this
file (users are prompted for password in early boot instead)
2)the 'luks' option is the default option so it is possible for
/etc/crypttab entries to never have this set explicitly and any
block device configured as such is currently missed
3)any device mounted manually, or using any other mechanism aside
from /etc/crypttab will be missed
This commit executes 'cryptsetup isLuks' on every block device in
the system to determine whether it is a LUKS device. This handles
all 3 cases mentioned above and closes issue #615.
Test case wording was also updated to reflect the fact that it
only checks for LUKS encrypted block devices. So, plain dm-crypt
and …
> [CRYP-7930] Modify to use 'lsblk' and 'cryptsetup'

- db/software-eol.db
- Tested on Debian 10.
- use EOL or EOL LTS if exists (but not EOL ELTS)
> Add Debian EOL

- include/tests_authentication
This fixes #608.
`Register function` uses/overwrite variable `FIND` in 
https://github.com/CISOfy/lynis/blob/master/include/functions#L2571
so it needs to be registered before
https://github.com/CISOfy/lynis/blob/master/include/tests_authentication#L740
or use another variable like in this PR
Also I think there is a typo in 
> found one or more accounts with**out** expire date set
> Fix auth-9282

- include/osdetection
What kind of tool is this if it would fail to detect the oldest living distro?! :smile: 
The `os-release` can be seen here: <ftp://ftp.slackware.com/pub/slackware/slackware64-current/source/a/aaa_base/os-release>
> Slackware Linux OS detection

- include/functions
- include/tests_authentication
- include/tests_crypto
- include/tests_kernel
Hi again :)
Just like in https://github.com/CISOfy/lynis/pull/761 I added support for relative paths. So whenever someone uses something like
```
error_log  logs/error.log;
access_log  logs/access.log;
```
these log files are found now.
Tested with:
- bash 5.0.9
- dash 0.5.10.2
> nginx-test: add log file detection for relative paths

- include/tests_mac_frameworks
If the tool exists but the kernel doesn't have grsec, you'll get the
following error into stderr:
Could not open /dev/grsec.
open: No such file or directory
> Redirect gradm stderr to /dev/null

- include/binaries
- include/functions
- include/tests_authentication
- include/tests_crypto
- include/tests_kernel
Hi,
I noticed the "ToDo" comment in the tests_kernel regarding the checks for disabled coredumps. So I added the checks.
I just hope I wrote the checks like had them in mind. Please let me know if you would like to have some changes.
**Edit:** Forget to mention, that it was tested on/ with:
- Manjaro 18.1
- ArchLinux 4.79
- RedHat 6
- bash 4.1.2
- bash 5.0
- dash (on RedHat 6 and on Arch)
Various commands have been verified on AIX, HPUX and Solaris as well (couldn't upload and run the full script on these servers though).
----------------------
In addition I fixed a few issues I came across. For example:
```
FIND1=$(${GREPBINARY} -r -v "^#" ${ROOTDIR}etc/security/limits.conf ${LIMITS_DIRECTORY} | ${AWKBINARY} -F ":" '{print $2}' ...
```
The option "-r" for grep doesn't exist on older AIX …
> KRNL-5820: add checks for disabled coredumps in systemd & etc/profile

- include/tests_kernel
Forgot a commit. Added missing variables now.
Also I replaced regex "\s*" with " *" in this test as well, after I discovered today, that "\s*" doesn't work under HPUX and Solaris.
> add missing variables and replace '\s' to be posix conform

- include/tests_storage
Also avoid false positive in lynis-sdk, plus the usual double quote to prevent globbing and word splitting
> Clean shellcheck warnings in STRG-1846

- include/tests_crypto
Hi,
This should fix #781 and allow compatibility with older Linux systems where lsblk doesn't support --paths yet.
Tested with bash and dash on Manjaro and Arch.
I'm going to post this pull request already and could run a test on RedHat 6 next week Mo or Tue if requested.
> fix for #781 - run lsblk without --paths

- include/profiles
grep doesn't work with '\|' in AIX. grep -E is more POSIX compliant.
Without this fix, lynis doesn't work at all
> First fix in order make lynis work OK in AIX

- include/tests_php
Should fix #780
Added a few more paths to php.ini files and php.conf.d folders - especially the ones reported in that issue.
I noticed that folders have to be added for each new PHP version and that some paths for PHP7.2 were missing and for PHP7.3 there had been no paths yet, so I added that as well.
@mboelen Maybe we (actually hope it is you :stuck_out_tongue: ) should rework the PHP test a bit to avoid the necessity to add new folders for each PHP version?
I'll ask for a test again, but already created this pull request for reference.
> added additional php folders to check, plus added PHP72 and PHP73

- include/functions
A few changes to the HasCorrectFilePermissions function:
1.  Added a call to awk for CHECK_PERMISSION that verifies that the value is 3 digits long and appropriately padded with leading zeros.  This could be an issue if you ever wanted to check a file that did not have any permissions for owner or group.  Now this is an very rare occurrence but its now handled.
2.  Using the find binary needed to be called in a slightly different way for directories and files.  Much like ls.
3.  For the case statement for converting the ls output to octal, I found two issues.  First the existing check was looking for a single letter and would commonly fail.  I expanded it to look for the full string that it is mostly likely to see.  I have not included sticky bits because it looks like the awk command to …
> Updated permissions checks

- include/tests_authentication
- include/tests_printers_spools
Converted file permission tests from if statements to case statements.  This allows us to forgo the need to a chain of 'and/or' conditions and use some basic regular expressions.  Formatted the sudoers file tests so that the progress display looks the same but the log file will give the user a little bit more information on what needs to be updated.
This method seems easier to read to me, what do you think?
Dave
> Updated tests for file permissions to case statements

- include/tests_time
Fixes #794 
This variable must have been forgotten. 
Good catch by @liedekef
> do set variable NTP_CONFIG_FOUND if ntp config is found

- include/tests_ports_packages
Hi,
This should resolve  #788 and gets also rid of the same Exception on the Raspi.
I hope the changes make sense.
> KRNL-5840: add detection for proxmox and raspi kernel

- include/tests_homedirs
Fixes #773
```
ec2-user:x:501:501:EC2 Default User:/home/ec2-user:/bin/bash
[...]  
ec2-user:x:501:501:EC2  
Default  
User:/home/ec2-user:/bin/bash  
```
> Correctly split lines of /etc/passwd

- include/binaries
This could fix #768
I'll request a test in the issue. With my tests everything was alright, but could be different in a real world scenario.
Anyway: tested with bash and dash again.
> don't fail relative paths check with spaces in PATH

- include/tests_networking
NETW-3014 had its iterator name changed from ${I} to ${ITEM} 3 years ago but the report lines still reference ${I}. This reports the last thing ${I} was set to instead of the actual interface.
> NETW-3014: Report correct promisc interface

- include/tests_crypto
Initial version of CRYP-8004 (see #793).
There are few shortcomings:
* This will not detect all RNGs (for instance OneRNG registers itself as `/dev/ttyACM0` and not through Linux's HW RNG drivers)
* There is no verification that `rngd` is actually using the found HW RNG. It could as well be using `/dev/zero` etc. This can be implemented, but might require a bit more complex check, as the input can be configured in several places (conf files, cmdline parameters etc.).
> Added CRYP-8004

- include/tests_ssh
This option is deprecated since 2003. Having it in a config file raises
a warning and UseDNS (that is on by default) includes the
VerifyReverseMapping check.
See
https://github.com/openssh/openssh-portable/commit/3a961dc0d36c1f87788b707130f6d07709822d38
See #528
--------
I believe it's safe to remove a check for something deprecated for 17 years ;)
Cheers,
~Nico
> Remove the test for ssh config VerifyReverseMapping

- include/tests_authentication
HP-UX also has /usr/sbin/pwck. For trusted systems, two additional options -s (check inconsistencies with the protected password database) and -l (check encrypted password lengths that are greater than 8 characters) are available.
> AUTH-9228 for HP-UX

- lynis.8
Quotes have a special meaning when used at the start of line.
> Fix quote syntax error in manpage

- CHANGELOG.md
- include/tests_php
The expose_php configuration option is only relevant for non-cli PHP and
thus lynis should not look for it in config files that are for cli
Fix #849
> Skip the PHP cli configuration file when looking for expose_php

- include/tests_filesystems
HP-UX: /usr/sbin/mount reports "/home on /dev/…", so $1 has to be used
> FILE-6310 for HP-UX

- include/tests_kernel
The Raspberry Pi kernels reside within raspberrypi-kernel package[1].
[1] https://www.raspberrypi.org/documentation/linux/kernel/updating.md
> KRNL-5788 in Raspi: don't complain about missing /vmlinuz

- include/tests_kernel
Hi,
I noticed one issue at first and when I attempted to fix that, I discovered other issues as well, which should be fixed by my changes.
**Problem:**
The check for the kernel version fails with an error output on Raspbian and probably also on other unix systems where vmlinuz image is missing.
The output from lynis 3.0.0 master (latest version per Jan 26th):
```
- Checking setuid core dumps configuration                [ DISABLED ]
Usage: file [-bcCdEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding]
[--mime-type] [-e <testname>] [-F <separator>]  [-f <namefile>]
[-m <magicfiles>] [-P <parameter=value>] <file> ...
file -C [-m <magicfiles>]
file [--help]
=================================================================
Exception found!
Function/test:  [KRNL-5830:4]
Message: …
```
> restructered test and fixed vmlinuz detection

- include/tests_ssh
fix CISOfy/lynis#844
pre: major version >= 5 and minor version >= 1
post: major version > 5 or (major version == 5 and minor version >= 1)
> [SSH-7408] fix OpenSSH server version check

- include/tests_boot_services
Log lines for running and enabled services were mixed up, fix.
> Fix logging of running and enabled services

- include/tests_kernel
If /etc/kernel-img.conf has the line do_symlinks=No, Debian (probably
also Ubuntu) kernel packages will not update /vmlinuz
etc. symlinks. In that case, guess the kernel from uname -r.
> Check if /vmlinuz is missing due to /etc/kernel-img.conf

- db/tests.db
- include/binaries
- include/tests_networking
'resolvectl statistics' shows if DNSSEC is supported by
systemd-resolved and upstream DNS servers.
> Check DNSSEC status with resolvectl when available

- include/binaries
- include/tests_mac_frameworks
Display and log: permissive types (rules are not enforced), unconfined
processes (not confined by rules) and processes with initrc_t
type (generic type with weak rules).
> Enhance SELinux checks

- db/software-eol.db
- include/osdetection
Slightly modify how the EOL lookup works in osdetection by changing the
semantic meaning of an empty date field (field 3). If this field is empty then
the EOL for the OS is false (0). This is much clearer than setting a date far
in the future. There are some OS that have a rolling upgrade (Arch Linux)
and others that EOL older releases after a certain number of (major) releases
have past (NetBSD).
Add EOL data for NetBSD based on NetBSD's general policy of marking a
release EOL one month after the second succeeding major release.
> Add NetBSD EOL

- include/tests_authentication
- plugins/plugin_pam_phase1
Use `!` rather than the non-standard `find(1) -not` operator.
> Fix uses of non-standard find not operator

- include/tests_boot_services
Linux is the only OS with systemd so no need to check for systemd
single user mode on other operatings systems.
> Make BOOT-5260 Linux only

- plugins/plugin_pam_phase1
PAM rules may have a leading '-' character to indicate that if the
module is missing, the error will be ignored, so let's ignore it in
the check.
> pam: ignore leading dash

- include/tests_authentication
This adds NetBSD in to the supported OSes for AUTH-9234. It is possible that this could could be shared with OpenBSD. It was kept separate in case OpenBSD does not support a `/etc/usermgmt.conf` file for setting the default `useradd(8)` UID range.
> Add AUTH-9234 for NetBSD

- include/tests_authentication
Add FreeBSD and NetBSD as both support PAM. Simplify the `PREQS_MET`
set test by using a case rather than a long if or.
> Add FreeBSD and NetBSD to AUTH-9268

- plugins/plugin_systemd_phase1
Process output from journalctl (v245) like: "Archived and active
journals take up xxx.xM in the file system."
> Fix journalctl output parsing for recent journalctls

- CHANGELOG.md
- db/tests.db
- include/binaries
- include/tests_boot_services
'systemd-analyze security' makes a nice overall evaluation of
hardening levels of services in a system. More details can be found
with 'systemd-analyze security SERVICE' for each service.
> Run 'systemd-analyze security'

- db/tests.db
- include/tests_authentication
-  #874 checked hashing methods in `/etc/{password,shadow}`, but user password hashing rounds isn't configured in `${ROOTDIR}etc/login.defs`.
- Add `AUTH-9230`, `Check group password hashing rounds`. The `SHA_CRYPT_MIN_ROUNDS` and `SHA_CRYPT_MAX_ROUNDS` options in `${ROOTDIR}etc/login.defs` "only affect the generation of group passwords. The generation of user passwords is done by PAM and subject to the PAM configuration." (http://man7.org/linux/man-pages/man5/login.defs.5.html)
- Accidentally caught a couple of tabs.
> Add test for group password hash rounds

- include/tests_filesystems
There should not be any need for char/block devices in /var, so
propose nodev. Sockets are not affected.
Check also /dev for noexec,nosuid and /run for
nodev,nosuid. Historically there was /dev/MAKEDEV script but that's
long gone.
In case a file system is not found in /etc/fstab, check if they are
mounted otherwise (e.g. via systemd mount units).
> Harden mount options for /var, check also /dev and /run

- include/binaries
- include/tests_time
This fixes #518.
Summary of changes:
- Enhancements:
- Search for the `ntpctl`binary.
- Check if OpenNTPD is installed by checking if `ntpctl` is installed.
- Confirm the use of OpenNTPD by confirming `ntpctl` is working or an process with the commandline `ntpd: ntp engine` exists.
- Add typical OpenNTPD configuration files to TIME-3170.
- New tests:
- TIME-3180: Report if ntpctl cannot communicate with OpenNTPD
- TIME-3181: Check status of OpenNTPD time synchronisation
- TIME-3182: Check OpenNTPD has working peers
This has been tested on FreeBSD
> Add detection of OpenNTPD

- include/tests_filesystems
Check if FS modules are blacklisted, also suggest 'blacklist module'
instead of obsolete syntax.
> FS module tests: check if modules are blacklisted

- include/tests_memory_processes
The prelink package is Linux specific no need to check for it on
non-Linux systems.
> PROC-3802 Only check for prelink package on Linux

- include/tests_ports_packages
The comment is correct. It is FreeBSD pkg not NetBSD pkg.
> Fix PKGS-7301 message nit

- include/tests_authentication
This fixes a bug where it was determined that /etc/login.defs didn't
exist as a prerequisite but then wasn't used to skip the test. Prevents
warnings from `grep(1)` for "no such file or directory".
> Fix AUTH-9230 for systems without /etc/login.defs

- include/binaries
- include/functions
These changes will remove numerous errors when `PackageIsInstalled` is called on a system using pkgsrc (e.g. NetBSD). It still does not solve the underlying issue with `PackageIsInstalled` doesn't work correctly on BSD systems where the core/base commands/daemons are not tracked as packages but considered part of the (core) OS.
> Add pkg_info

- include/tests_authentication
Use the standard `sort(1)` short option `-u` rather than `--unique`,
since not all versions support long options.
> AUTH-9229 Do not use long options for sort

- include/tests_authentication
DragonFly also supports PAM. Rework to use the `--os` option of `Register`
rather than `--preqs-met` as the former can support a list.
> AUTH-9268 Add DragonFly

- db/tests.db
- include/tests_authentication
All of the BSD based OSes have `/etc/master.passwd`. Make AUTH-9218 work for all removing
redundant AUTH-9489 for DragonFly. For all BSD OSes `/etc/master.passwd` is only readable
by root so additional condition to test registration.
> AUTH-9218 Improvements

- include/tests_crypto
[CRYP-7902] Checks for SSL_CERTIFICATE_PATHS_TO_IGNORE fails to ignore sub-directories #902
>  [CRYP-7902] Fixes issue #902

- CHANGELOG.md
- include/tests_kernel
Hello,
I'm not sure if such a feature is wanted in the project. Raspian doesn't have a standard way to inform a user about required reboots yet (as far as I know). That's probably the reason why lynis doesn't detect a required reboot yet.
I wrote a few lines which works around the missing standard way in Raspbian by simply comparing the build date of the current running kernel with the package date of the latest installed kernel package.
This test only starts if the check for a required reboot has no result so far and if there is a raspberrypi-kernel package file. So this test should not interfere with test results on other systems. Running these changes on other OS (Arch) didn't cause any issues.
It is successfully tested on my raspi with bash and dash.
I'm curious what you think about …
> extended test KRNL-5830 to detect required reboots on Raspbian

- CHANGELOG.md
- db/tests.db
- include/binaries
- include/tests_crypto
Add test CRYP-7931 to check if the system uses any encrypted swap
devices.
> Check if system uses encrypted swap devices

- include/functions
Lynis currently doesn't accept stricter file permissions.
E.g.:
```
~/lynis$ sudo ./lynis show details FILE-7524 | grep -i grub
2020-04-22 07:54:06 Test: checking file/directory /boot/grub/grub.cfg
2020-04-22 07:54:06 Test: checking if file /boot/grub/grub.cfg is 600
2020-04-22 07:54:06 Outcome: permissions of file /boot/grub/grub.cfg are not matching expected value (400 != 0600)
2020-04-22 07:54:06 Test: checking file/directory /boot/grub2/grub.cfg
2020-04-22 07:54:06 Skipping file/directory /boot/grub2/grub.cfg as it does not exist on this system
2020-04-22 07:54:06 Test: checking file/directory /boot/grub2/user.cfg
2020-04-22 07:54:06 Skipping file/directory /boot/grub2/user.cfg as it does not exist on this system
```
After change:
```
~/lynis$ sudo ./lynis show details FILE-7524 | …
```
> accept more restrictive file permissions

- include/osdetection
This pull request adds support for Oracle Linux, an EL derivative. closes #924
> Added OS detection for Oracle Linux

- include/tests_networking
This PR updates the hostname test in `NETW-2400` to allow uppercase characters in the validation regex.
* Created a virtual machine (vagrant & virtualbox)
* Set the VM's hostname to include uppercase characters: `sudo hostname ASDF`
* Cloned repo, entered the `lynis` directory, and checked out the `master` branch
* Ran `lynis`: `./lynis audit sytem`
* Parsed the output for `Hostname contains invalid characters [NETW-2400]`
* Checked `/var/log/lynis.log` for error log:
```
2020-06-02 14:53:32 Result: unexpected characters discovered in hostname (characters: ASDF), which may impact network connectivity
```
---
* Checked out the bugfix branch
* Ran `lynis`: `./lynis audit sytem`
* Noted the warnings count has reduced by 1 and NETW-2400 is not reported as an issue
* …
> Adds uppercase option to the hostname validation regex

- lynis
CVE-2020-13882: discovered by Sander Bos, code submission by Katarina Durechova - Store log and data file in home directory for non-privileged usage
> CVE-2020-13882: discovered by Sander Bos, code submission by Katarina Durechova - Store log and data file in home directory for non-privileged usage

- include/tests_crypto
Redirected stderr to /dev/null to silence output of `cryptsetup status /swap.img`
This was causing error output from my cron script.
Otherwise, if the swap file is not encrypted then the following error will be printed:
`Device swap.img not found`
> fix stderr output from cryptsetup status

- include/osdetection
Added the new [macOS Big Sur (11.0)](https://www.apple.com/newsroom/2020/06/apple-introduces-macos-big-sur-with-a-beautiful-new-design/) to osdetection.
> Add macOS Big Sur (11.0)

- include/tests_kernel
When KRNL-5728 locates the kernel config it does not properly set LINUXCONFIGFILE
if config is found as /proc/config.gz. This causes KRNL-5730 to fail due to missing prereqs,
despite a kernel config existing.
> Fix KRNL-5730 to properly check /proc/config.gz

- include/tests_authentication
Fixes #968 by moving the existing case statement in AUTH-9229 into its own function.
> [AUTH-9229] resolving syntax error on MacOS Catalina

- db/software-eol.db
Add EOL support for SUSE Linux Enterprise Server 12 and SUSE Linux Enterprise Server 15.
I believe this closes #965
> add SUSE Linux Enterprise Server EOL

- include/osdetection
Fix for https://github.com/CISOfy/lynis/issues/964 - POP OS added to include/osdetection
> Fix for Issues #964 - Pop!_OS added to osdetection

- include/tests_filesystems
I think we don't want to grep files in modprobe.d when dir is empty. Uses same approach as in USB-1000.
> [FILE-6430] Don't grep nonexistant modprobe.d files

- include/binaries
> add Microsoft Defender ATP, malware scanner

- include/osdetection
Added the [Alpine Linux](https://alpinelinux.org/) to osdetection.
> Adding Alpine Linux to OSDetection

- db/tests.db
- include/tests_time
Detect timesyncd by looking in the process list instead of timedatectl. The check if time was successfully synchronized is in the new test `TIME-3185`.
Closes #953.
> Fix timesyncd detection on systems without dbus.

- include/tests_time
This pull request detects the use of `sntp` and `ntpdig`.
As I worked at the same area of code discussed in #826, I fixed it as well.
> [TIME-3104] Find more time synchronization commands

- default.prf
The old rsh (remote shell) authorizes users and hosts in the files `/etc/hosts.equiv`, `.rlogin`and `.rhosts`. If attackers can write to those files, he can logon as a different to the system. While the rsh daemon usually checks for non-root owners or write permission, this may not be the case on any system.
Those files are also used by SSH if host based authentication is enabled. In addition to the files used by rsh, `.shosts` and `shosts.equiv` are used.
While the use of rsh is highly discouraged, it may still be in running on legacy systems. As those files are also used by OpenSSH, they are even relevant today.
This PR adds those files to the list of checked files.
> rsh host file permissions

- include/tests_time
In #824 I made a few mistakes:
- All tests:
- To test if the test should run, I checked against `NTPD_RUNNING` instead of `NTP_DAEMON_RUNNING`.
- Additionally, I used `==` instead of  `=` when testing if the daemon is openntpd. While this works on some systems, this is non standard and does not work at all on BSDs (where OpenNTPD is usually installed).
- TIME-3182:
- The regex for the peers was wrong (never matched anything) and instead of checking for an empty string (`-z`) it was checked for non empty (`-n`).
Thus the previous implementations were completely broken (TIME-3180, TIME-3181, TIME-3182). With this pull request I fix my own errors.
> [TIME-3180, TIME-3181, TIME-3182] Fix OpenNTPD tests

- CHANGELOG.md
- default.prf
- include/tests_crypto
Check also certificates in DER (*.cer, *.der) format. Add
/etc/refind.d/keys to list of certificate paths.
> [CRYP-7902] Check also certificates in DER format

- db/software-eol.db
- include/osdetection
Add Mageia EOL dates and `/etc/redhat-release` is a link to `/etc/mageia-release`.
Ref https://github.com/CISOfy/lynis/issues/1034
> Mageia got /etc/os-release and add Mageia EOL dates

- include/osdetection
Fixes cisofy/lynis#1014.
Flatcar is a fork of CoreOS. Thus the variable LINUX_VERSION_LIKE
(introduced with #1004) for Flatcar is CoreOS.
> Add support for Flatcar Container Linux

- include/functions
Includes can be absolute paths too. This is quick fix counting on fact that absolute paths have slash at start.
Second commit is similar to my previous PR, IMHO Lynis should not output ls errors on empty included directories.
> Support absolute paths in nginx includes and fix ls warning on empty directories

- include/tests_time
This PR fixes #1012. As Ubuntu 18.04, which has systemd version 237 does not make a file at `/run/systemd/timesyncd/synchronized` I changed the `SYNCHRONIZED_FILE` to `/var/lib/systemd/timesync/clock`, which **is** created by systemd version 237.
This shouldn't cause any issues for later systemd versions as `/var/lib/systemd/timesync/clock` is still used besides `/run/systemd/timesyncd/synchronized` [(see the manual of the latest systemd version)](https://www.freedesktop.org/software/systemd/man/systemd-timesyncd.service.html).
**Update**: I have now modified the PR such that it still uses `/run/systemd/timesyncd/synchronized` first and uses `/var/lib/systemd/timesync/clock` and `/var/lib/private/systemd/timesync/clock` as fallback options in case `/run/systemd/timesyncd/synchronized` …
> [TIME-3185]: Change timesyncd synchronization file

- include/functions
Some distributions or OS:es might be missing `pgrep`, besides AIX.
Closes #1041
> require pgrep before usage

- include/binaries
- include/tests_malware
Catch the Synology Antivirus Essential malware scanner.
Closes #1050 
> add Synology Antivirus Essential malware scanner

- db/software-eol.db
- include/tests_kernel
Added Alpine Linux EOL dates for current versions with support and most recent version out of support.
Improve detecting kernel version on disk. Alpine uses /boot/vmlinuz-lts which was being detected as version 'lts' which did not match the current version of the kernel in memory. This caused the code to incorrectly identify a reboot as needed.
> Alpine Improvements

- include/tests_authentication
Hi guys, I am very excited since this is my very first contribution into this project.
I basically added a test to gather information about locked accounts following the guidelines of @chr0mag as mentiones in issue #474. Furthermore, I removed the system locked accounts as @chr0mag and @mboelen consensued in the same issue.
Any feedback is appreciated.
> [AUTH-9284] Feature: gather locked accounts info

- include/tests_accounting
Fixes #986. It assumes the timer units are enabled together with sysstat.service. This at least happens on CentOS 8.
> [ACCT-9626] Detect sysstat systemd unit

- include/profiles
The first od is removed, the second time is moved to right before echoing
the characters. On certain OpenSolaris distributions, `od` always outputs
spaces, even if the input is empty. The spaces would have been converted
to !space!, thus Lynis detected invalid characters / old style configuration.
Resolves cisofy/lynis#1065.
Signed-off-by: Simon Biewald <simon@fam-biewald.de>
> Use `od` only for displaying invalid characters

- include/tests_networking
Solaris' tr does not support full regular expressions.
> Simplify tr hostname checking expression

- db/software-eol.db
- include/osdetection
This PR adds detection of OpenSolaris distributions. The variable OPENSOLARIS is introduced to distringuish between the closed  source Solaris or OpenSolaris based ones. The edge case of OpenSolaris itself is not yet solved, but OpenSolaris itself should be very rare these days. Solaris Express is not detected yet as well.
Lynis will try to read the `/etc/os-release` if possible and will fall back to parsing the free form `/etc/release` file.
Currently detected and distinguished (Open)Solaris variants with correct version number are:
- Solaris >= 11 (exluding Solaris Express and OpenSolaris) as "Oracle Solaris" with EOL dates for 11.3 and .4
- Solaris < 11 as "Sun Solaris" 
- OmniosCE (but not old Omnios) with EOL dates
- OpenIndiana (Hipster and Legacy)
- Shillix
- SmartOS
- Tribblix
- …
> OpenSolaris distribution detection

- include/tests_boot_services
Part of the Solaris fixes of #1007, but is likely relevant for other operating systems as well.
> Test if /etc/grub.d is a directory

- include/functions
Fixes CISOfy/lynis#1075.
Before this commit, the interfaces "e1000g1" and "net0" were allowed. The name "e1000g0" is appended to the list. After finding an interface, the loop is interrupted now. As previously "net0" was always used, even if another interface was available, the list is reordered to "net0 e1000g1 e1000g0" to not break previous generations.
A typo is also fixed ("No interface found op Solaris ..." -> "No interface found on Solaris ...").
Signed-off-by: Simon Biewald <simon@fam-biewald.de>
> Use first e1000 interface and break after match (for hostid generation on Solaris)

- include/binaries
Fixes cisofy/lynis#1078.
Signed-off-by: Simon Biewald <simon@fam-biewald.de>
> Quote binary variables during SUID/GID enumeration

- db/tests.db
- include/binaries
- include/tests_boot_services
The Solaris ~~IPS~~ SFM service manager (svcs) is now detected, and services
managed with it are enumerated.
Test BOOT-5184 now runs on Solaris, too, as SysV init scripts are
supported as well, even with ~~IPS~~ SFM. SysV Init has been the traditional
init system on Solaris and is used in previous versions.
> Add support for Solaris services, run BOOT-5184 there

- db/tests.db
- include/tests_logging
On Solaris, the name loghost can be used to point to remote log servers.
By default loghost is configured to 127.0.0.1, logging to the local
machine.
Thus a new test - LOGG-2153 - is created to test if loghost is not
localhost and LOGG-2154 is modified to ignore @loghost lines if loghost
is localhost.
> Test if loghost is not localhost

- CHANGELOG.md
- default.prf
Add checks for sysctls recommended by CLIP OS (vanilla kernel sysctls
only):
https://docs.clip-os.org/clipos/kernel.html#sysctl-security-tuning
> [KRNL-6000] Check more sysctls

- include/tests_authentication
Since if only one of the MIN or MAX values is set, and then this value will be used, we only have to fail AUTH-9230 if both SHA_CRYPT_{MIN,MAX}_ROUNDS are undefined.
Closes #1085 
> only fail AUTH-9230 if both SHA_CRYPT_{MIN,MAX}_ROUNDS are undefined

- include/tests_databases
Fix for Test: DBS-1816 - Check empty MySQL root password
> Fix for MariaDB test ID DBS-1816

- include/consts
- include/osdetection
- include/tests_boot_services
- include/tests_kernel
- include/tests_ports_packages
Before parsing /etc/debian-release and /etc/lsb-release,
it is now checked if the variable LINUX_VERSION is already set.
This fixes cisofy/lynis#1003.
This will affects Ubuntu and Debian based distributions, like:
- Pop!_OS (Ubuntu based)
- Kali (Debian Based)
- Raspbian
- ...
Unfortunately this will likely skip/brake a few tests for those distributions, as they are not considered to be Ubuntu or Debian anymore. Linux Mint was already detected properly, but at least some tests already had support for them (will other tests for Ubuntu are skipped). See below for an included fix.
Those are tests I identified that will be skipped incorrectly with 529bcb2a6036718da41ef0bfc52fae7f20bdfcac:
- BOOT-5180: Check for Linux boot services (Debian style)
It was already skipped on Linux Mint.
- …
> Test for LINUX_VERSION before setting it again

- CHANGELOG.md
- db/tests.db
- include/tests_hardening
Examine /proc/sys/fs/binfmt_misc (Linux) for additional registered
binary formats. Those are probably emulated and their emulation could
be less tested, more buggy and more vulnerable than native binary
formats, so they should be disabled when not needed.
> Check for registered non-native binary formats

- include/tests_firewalls
```
$ nft -v
nftables v0.9.8 (E.D.S.)
$ sudo nft list ruleset --stateless 
Error: syntax error, options must be specified before commands
```
> nftables empy ruleset test fix by reorder --stateless

- include/tests_filesystems
> 1103: FILE-6430 reports suggestion only when at least one kernel module is not in the blacklist

- include/tests_logging
Metalog comes with its own kernel logger, so there is no need to also run klogd.
> [LOGG-2138] Do not check for klogd when metalog is being used

- include/osdetection
There is an `i686` fork of Arch Linux called [Arch Linux 32](https://archlinux32.org/). It's `/etc/os-release` reads as follows:
````
NAME="Arch Linux 32"
PRETTY_NAME="Arch Linux 32"
ID=arch32
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux32.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux32.org/"
BUG_REPORT_URL="https://bugs.archlinux32.org/"
LOGO=archlinux
````
> Added Arch Linux 32

- include/tests_ports_packages
`PKGS-7320` checks whether package `arch-audit` is installed. This test has been extended to test `${OS_FULLNAME}` for both "Arch Linux" as well as "Arch Linux 32".
> Test PKGS-7320 extended to "Arch Linux 32"

- include/osdetection
By request of #1179, in order to add Artix Linux to lynis.
> Adding Artix Linux to osdetection

- include/osdetection
> Fix typo on Artix OS Detection

- include/osdetection
Fixed the macOS Big Sur (Version 11) detection and added support for macOS Monterey (Version 12)
> Fix Big Sur Detection and add macOS Monterey

- include/tests_filesystems
Recent AWS Ubuntu images have incorporated Linux kernel 5.8. [This kernel version](https://github.com/systemd/systemd/issues/16896#issuecomment-683201305) allows [new textual values](https://www.kernel.org/doc/html/latest/filesystems/proc.html#chapter-4-configuring-procfs) for hidepid.
Support these textual values. For [new hidepid=4](https://lwn.net/Articles/817137/), I have arbitrarily chosen to retain the same hardening points as hidepid=2.
> Kernel 5.8 permits hidepid textual values

- include/tests_file_integrity
When using Ubuntu 21.10 and `aide` version 0.17.3-1, the database configuration setting has changed from `database=` in previous versions to `database_in=`.
This PR catches `(^database|^database_in)=`
```sh
~$ lsb_release -d && dpkg -l | grep aide* | awk '{print $2, $3}' && grep -E '(^database|^database_in)=' /etc/aide/aide.conf
Description:    Ubuntu Impish Indri (development branch)
aide 0.17.3-1
aide-common 0.17.3-1
database_in=file:/var/lib/aide/aide.db
```
```sh
~$ lsb_release -d && dpkg -l | grep aide* | awk '{print $2, $3}' && grep -E '(^database|^database_in)=' /etc/aide/aide.conf
Description:    Ubuntu 20.04.2 LTS
aide 0.16.1-1build2
aide-common 0.16.1-1build2
database=file:/var/lib/aide/aide.db
```
> add support for additional Aide db paths

- include/tests_ports_packages
This fixes the bug I've encountered #1230, by adding `Garuda Linux` to the valid `$OS_FULLNAME` to be tested.
If any other changes are needed, feel free to tell me @mboelen or any other maintainer of this repo.
> Add Garuda Linux to audit package test tool

- include/tests_filesystems
- include/tests_networking
This PR:
- Allows unknown number of spaces when blacklisting kernel modules
- Closes #1219 
> allow unknown number of spaces in modprobe blacklists

- include/tests_printers_spoolers
When searching for the"Port" statement, the result would overwrite the result from the "Listen" search.
This would lead to a false-positive result, when there was only a Listen statement for localhost.
Flipping the order of the two searches and keeping track of the first result in a separate variable fixes the problem.
> Dont write over FIND variable. Fixes #1021

- include/tests_authentication
`pam_tally2` was removed in [PAM 1.5.0](https://github.com/linux-pam/linux-pam/releases/tag/v1.5.0) and `pam_faillock` has replaced it.
Also the check for `${ROOTDIR}etc/pam.conf` is not sufficient to determine if PAM is being used (at least in upcoming Slackware 15.0) so I added additional check for `${ROOTDIR}etc/pam.d` directory.
> Check for pam_faillock in AUTH-9408

- include/tests_kernel
Changes the user facing output to display a full path, allowing the user to
better grasp which security/limits.conf file is affected.
fix issue #1264
> [KRNL-5820] additional path for security/limits.conf

- include/tests_filesystems
This PR:
- adds `plocate` to `LOCATE_DBS`
- sorts the `LOCATE_DBS` paths
- closes #1288 
> add plocate

- include/tests_ssh
This PR:
- Removes the Compression test for `sshd` versions > 7.4
- Closes #1291
> Only test Compression if sshd version < 7.4

- include/functions
Add extra check to verify the linux OS supports nanoseconds. This might not be the case with certain busybox implementations.
> Verify the linux OS supports nanoseconds

- db/software-eol.db
Sources:
AL2023 EOL: https://docs.aws.amazon.com/linux/al2023/release-notes/support-info-by-support-statement.html#support-info-by-support-statement-eol
AL2 EOL: https://aws.amazon.com/amazon-linux-2/faqs/
AL EOL: https://aws.amazon.com/blogs/aws/update-on-amazon-linux-ami-end-of-life/
> Update Amazon Linux EOL dates and add Amazon Linux 2023

- include/binaries
- include/tests_time
- lynis
Hello,
recent /usr/bin/egrep on Linux systems is throwing annoying warning that egrep is obsolete and that grep -E is used instead. 
To avoid this warning the EGREPBINARY is set to "${GREPBINARY} -E" if it has extended regexp in the "--help"
Best regards
Michal Ambroz
> use grep -E instead of egrep if possible

- include/osdetection
This allows detection the OpenEmbedded "nodistro" and The Yocto Projects distro "Poky"
> osdetection: add OpenEmbedded and Poky

- db/software-eol.db
software-eol.db: Add new Debian/Ubuntu releases and update EOL dates
> software-eol.db: Add new Debian/Ubuntu releases and update EOL dates

- include/osdetection
Adds support for macOS Ventura (13.x) and Sonoma (14.x)
Fixes #1370
> osdetection: add macOS Ventura and Sonoma

- db/tests.db
- include/tests_insecure_services
- include/tests_system_integrity
- include/tests_tooling
- This pull request fixes a few missing or erroneous test number comments. i.e.:
_# Test        : INSE-8322
Register --test-no INSE-8322 --package-manager-required --weight L --network NO --category security --description "Check if telnet server is installed"_
- Also fixes a couple of test numbers in tests.db that were wrong according to the actual test definitions in include/tests_*
> Fixing missing or erroneous test number comments

- include/tests_ports_packages
- This PR closes issue #1277 
- These were the changes that made test PKGS-7322 fail:
https://github.com/ilpianista/arch-audit/commit/d1ca0c27114db90a0e6d2ae60c8f42a76800933e
https://github.com/ilpianista/arch-audit/commit/993b5b43a86928e11c893cde9cb524b27158d10a
- Tested in Arch Linux
- This is the kind of output to expect in lynis-report.dat:
_vulnerable_package[]=openssl,arbitrarycommandexecution.|
vulnerable_package[]=perl,signatureforgery,directorytraversal.|
vulnerable_packages_found=1_  
_vulnerable_package[]=curl|cve=CVE-2016-9594,CVE-2016-9586.|
vulnerable_package[]=gst-plugins-bad|cve=CVE-2016-9447,CVE-2016-9446,CVE-2016-9445.|
vulnerable_package[]=libtiff,denialofservice.|_
> Updating parsing of arch-audit since arch-audit modified its output. Issue 1277

- include/tests_databases
- I assume the issue reported ( #1300 ) is related to this (from xargs manual page):
_-i[replace-str], --replace[=replace-str]
This option is a synonym for  -Ireplace-str  if  replace-str  is
specified.   If  the replace-str argument is missing, the effect
is the same as -I{}.  This option is deprecated; use -I instead_
- Tested in Debian. Can't test on Freebsd.
- This PR closes #1300
> Replacing deprecated option -i. Issue 1300

- include/tests_databases
On FreeBSD, the Redis configuration file is typically stored as /usr/local/etc/redis.conf.
> Update tests_database: Redis configuration file

- include/tests_databases
This PR:
- uses the`${FINDBINARY}` to locate redis.conf if  the /snap directory exists
- closes issue #1327 
- remove some end-of-line whitespaces
> find redis.conf if /snap directory exists 

- include/tests_databases
Tested on almalinux8/9, rockylinux9 and freebsd13.
Support postmaster as possible servicename.
Support correct (default) location per OS.
use new xargs -I syntax, else it breaks on FreeBSD.
> postgresDB fixes for almalinux, rockylinux and freebsd.

- include/functions
Slackware's `pkgtools` doesn't seem to have "is this package installed" functionality, but all the packages can be seen in `/var/lib/pkgtools/packages/` (though that path was introduced/changed in the recent [Slackware 15.0](https://ftp.osuosl.org/pub/slackware/slackware64-15.0/ChangeLog.txt)).
E.g. now with the `INSE-8000` test it now sees the file `inetd-1.79s-x86_64-14` (the suffix is version-arch-revision) and flags it as installed.
> Added Slackware support for PackageIsInstalled() function

- include/tests_containers
When running lynis audit system as a non-privileged user, and assuming dockerd running as root, lynis will report an ERROR por Docker status but will report NONE for "Docker info output (warnings)", not reporting the error ("Docker daemon socket") that docker info reported. 
This pull request makes sure that error is reported and the hardening points are consistent with that error.
> Checking for errors, not only warning in docker info output

- include/functions
`apk search` lists all packages that have `${package}` on the name and that aren't installed
Example for rsh (not installed)
```
$ apk search rsh 2> /dev/null | grep rsh
abseil-cpp-flags-marshalling-20230802.1-r0
harsh-0.8.30-r0
powershell-7.3.9-r0
starship-1.16.0-r0
starship-bash-completion-1.16.0-r0
starship-fish-completion-1.16.0-r0
starship-zsh-completion-1.16.0-r0
starship-zsh-plugin-1.16.0-r0
$
```
```
$ apk list --installed rsh 2> /dev/null | grep rsh
$
```
Example for busybox (installed)
```
$ apk search busybox 2> /dev/null | grep busybox
busybox-1.36.1-r15
busybox-binsh-1.36.1-r15
busybox-doc-1.36.1-r15
busybox-extras-1.36.1-r15
busybox-extras-openrc-1.36.1-r15
busybox-ifupdown-1.36.1-r15
busybox-mdev-openrc-1.36.1-r15
busybox-openrc-1.36.1-r15
busybox-static-1.36.1-r15 …
```
> Fixed Alpine Linux installed package detection

- include/tests_logging
As mentioned in https://github.com/CISOfy/lynis/issues/1316, Wazuh is a fork of OSSEC and is being actively maintained. Wazuh agent has capabilities to read, filter, process and enrich logs including syslog by default. The SIEM capability is based on the central log collection. Therefore, it seems feasible to add wazuh-agent to the accepted logging products. Current capabilities satisfy [test LOGG-2154](https://cisofy.com/lynis/controls/LOGG-2154/).
https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/
https://documentation.wazuh.com/current/pci-dss/log-analysis.html
> Added wazuh-agent as a remote syslog capability

- include/tests_malware
As of 1 Oct 2023, McAfee antivirus for Linux has been deprecated https://www.mcafee.com/support/?locale=no-NO&articleId=TS103384&page=shell&shell=article-view
> McAfee antivirus has been deprecated

- include/tests_authentication
This pull request just adds the name of the latest package (libpam-passwdqc) for checking password strength used in Debian and Ubuntu distributions. Solves issue https://github.com/CISOfy/lynis/issues/1354
Run test AUTH-9262 with and without the package just to make sure the behaviour was as expected. Debian 12.
> Change in suggestion message. Issue 1354

- include/tests_mac_frameworks
It's not installed everywhere, causing this error message:
/usr/share/lynis/include/tests_mac_frameworks: line 161: permissive: command not found
/usr/share/lynis/include/tests_mac_frameworks: line 162: permissive: command not found
> tests_mac_frameworks: check for existance of semanage binary

- include/tests_networking
I changed the check `/bin/true` to `/bin/(true|false)` to be more inclusive and eliminate false positives for those who use `/bin/false` instead.
> Added regex for NETW-3200 in tests_networking

- include/profiles
For busybox support, some commands don't support the newer syntax :alnum: :cntrl: etc options.
I replaced them with the older counterparts and in one case replaced upper->lower lower->upper with `awk` replacements. 
Only issue I can see if we are allowing for LOCALE specific optimizations for using `tr` with the posix callbacks. I suspect we aren't since in the `grep` statement on line 71 we use the ASCII syntax of a-z.
So I believe this patch will preserve functionality for all platforms, but if there is concerns on still using :alnum: I can submit revised patch where I check if the `tr` command supports advanced functionality and then everytime the `tr` command is about to run put an if statement. I thought this would be klunky given how many uses of `tr`
The test for `tr` functionality …
> Replace newer tr command syntax with older ascii specific operations

- include/osdetection
Running Lynis `master` on my Pinephone, it failed to detect the OS. Indeed, PostmarketOS was not yet included in the OS detection logic.
Here is the `/etc/os-release` for reference. 
```
PRETTY_NAME="postmarketOS v21.12.3"
NAME="postmarketOS"
VERSION_ID="v21.12.3"
VERSION="v21.12.3"
ID="postmarketos"
ID_LIKE="alpine"
HOME_URL="https://www.postmarketos.org/"
SUPPORT_URL="https://gitlab.com/postmarketOS"
BUG_REPORT_URL="https://gitlab.com/postmarketOS/pmaports/issues"
```
Let me know if I missed anything, or if more testing is required.
> osdetection: add PostmarketOS

- include/tests_malware
This PR:
- adds a check for the ESET Endpoint Antivirus `oaeventd` process
- closes #1285 
> add check for ESET oaeventd

- include/tests_malware
As mentioned in https://github.com/CISOfy/lynis/issues/1304, Wazuh is a fork of OSSEC and is being actively maintained. Wazuh agent has capabilities to detect and prevent malware and rootkits acting as an EDR. Therefore, it seems feasible to add wazuh-agent to the accepted antivirus and rootkit detection products. Current capabilities satisfy [test HRDN-7230](https://cisofy.com/lynis/controls/HRDN-7230/).
https://documentation.wazuh.com/current/user-manual/capabilities/anomalies-detection/index.html
https://documentation.wazuh.com/current/pci-dss/rootkit-detection.html
> Added Wazuh as a malware scanner/antivirus and rootkit detection tool

- .editorconfig
- include/osdetection
The `.editorconfig` file works for most modern editors. It ensures the indentation standards for the repository are consistent with what's in `CONTRIBUTING.md`. See [here](https://editorconfig.org/) for more settings.
Updated `include/osdetection` so it recognizes Google's Container-Optimized OS.
Running this on a COS instance in Google Cloud I get:
```
[+] Initializing program
------------------------------------
- Detecting OS...                                           [ DONE ]
- Checking profiles...                                      [ DONE ]
---------------------------------------------------
Program version:           3.0.8
Operating system:          Linux
Operating system name:     Container-Optimized OS from Google
Operating system version:  101
Kernel version: …
```
> Add .editorconfig and detection for Google's Container-Optimized OS

- include/tests_filesystems
This pull request fixes issue 1367: https://github.com/CISOfy/lynis/issues/1367
Tested on:
- Debian 11, kernel 5.10.0. Failure and success.
- Ubuntu 19.04, kernel 5.0, which skipped the test because on minor version 0. Failure and success.
> Fixing test on kernel major and minor version (FILE-6344). Issue 1367

- include/tests_crypto
This code will check if macOS FileVault is enabled.
> Added CRYP-7932 to determine if the system has enabled macOS FileVault.

- include/tests_ssh
In the evaluation of AllowGroups, AllowUsers was in the output text.  I have corrected this
> changed wording of the output AllowUsers to AllowGroups in test SSH-7440

- include/tests_ports_packages
- This PR closes issue #1275 
- Tested in Debian 11 and Debian 10.
> Checking debsums default file to make sure cron jobs are enabled. Issue 1275

- include/tests_kerberos
Fixes https://github.com/CISOfy/lynis/pull/1456#issuecomment-2113390171
> KRB-1010: Silence output when SKIPTEST != 0

- include/tests_kernel
```
ulimit: ulimit [-SHabcdefiklmnpqrstuvxPT] [limit]
```
> KRNL-5820: Accept ulimit with -H parameter also

- include/osdetection
Contents of `/etc/os-release`:
```bash
NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
LOGO=archlinux-logo
```
> Support Arch Linux ARM detection

- include/osdetection
Added Peppermint OS to the list (version codename returns "Bookworm", think it counts as the detailed version name)
PS: If you need it, the output of ``cat /etc/os-release``
````
PRETTY_NAME="PeppermintOS"
NAME="Peppermint"
ID=peppermint
VERSION_CODENAME="bookworm"
HOME_URL="https://peppermintos.com"
SUPPORT_URL="https://sourceforge.net/p/peppermintos/pepos/"
BUG_REPORT_URL="https://sourceforge.net/p/peppermintos/pepos/"
````
> Update osdetection - Peppermint OS

- include/tests_kernel
Fix runlevel detection for SO without systemd (eg. Slackware)
Close issue #1544
> Update tests_kernel -> KRNL-5622

- include/tests_firewalls
Hello, an adversary may use other than the `filter` table to manipulate the `netfilter` subsystem.
This PR adds `nat mangle raw security` tables in **FIRE-4508** control.
Please provide feedbacks!
Regards,
> FIRE-4508 - Adding more tables in ip4tables

- include/tests_webservers
The test for TraceEnable in Apache (HTTP-6660) has a comparison that is invalid in Dash (the default for /bin/sh in Debian-based distros). This is due to the way it does the string comparisons to try to compensate for an empty string (are there still shells around that need to do that?).
> HTTP-6660 - Wrap quotes properly for dash and other(?) shells

- include/tests_firewalls
Hello, with this patch I solved the following issue raised by the community:
- In some distributions, `sh` is a link to `bash`; this introduces some portability problemas while processing the `${IPTABLES_OUTPUT_QUEUE}` with `echo`; let's switch to `printf`.
- `AddHP` function was not removed from the parsing loop so it was not aligned with the module overall logic; let's increase the  `${IPTABLES_OUTPUT_QUEUE}` length from 4 to 6 to add hardening points and use them into the resume section.
- We were sorting the `${IPTABLES_OUTPUT_QUEUE}` even if it's empty; let's add a condition to avoid that.
Thanks!
> FIRE-4508 - Portability, hardening and output

- extras/build-lynis.sh
- include/functions
- include/osdetection
- plugins/plugin_systemd_phase1
1. Replaced "head -1" with "head -n 1"
> busybox devices don't recognize the option *-1*, anyway *head -n 1* works also in other distributions (e.g. Debian, macOS, ...)
2. Fixed Stat format error in busybox
> stat binary doesn't have the option *--format*, it was added a line to use this command also in busybox devices
3. Fixed find -printf error in busybox
> The command find in busybox doesn't have -printf option, to solve this it was used added *-exec stat -c %a {} \;*
4. SafeInput accept only alphanumeric values, underscore and hyphens
> in certain devices with busybox, *echo "$input" | sed 's/[^a-zA-Z0-9_-]//g'* is removing letters from the parameters (e.g. when executing *./lynis show profiles*)
> More support for busybox devices

- db/software-eol.db
- include/osdetection
This adds the latest macOS release and updates the EOL for macOS versions. I did not all all versions of macOS, would it make sense to add every small update @mboelen? 
Fixes #1565
> Add macOS Sequoia and update EOL

- db/software-eol.db
AL2:
As per https://aws.amazon.com/amazon-linux-2/faqs/:
> Amazon Linux 2 end of support date (End of Life, or EOL) will be on 2026-06-30.
AL23:
As per https://docs.aws.amazon.com/linux/al2023/ug/release-cadence.html:
> The maintenance phase ends June 30, 2029.
> Update Amazon Linux 2 and 2023 EOL

- include/tests_authentication
Add check for powerpc64le-linux-gnu location in PAM_FILE_LOCATIONS, rectifying failure to detect libpam-pwquality or libpam-passwdqc installed on powerpc hosts.
> Include powerpc64le on tests_authentication

- include/functions
This is a part of enabling support for OpenWrt, see: https://github.com/CISOfy/lynis/issues/1600.
(more details in commit messages)
> [OpenWrt] Fix HostID and HostID2 creation exceptions

- include/osdetection
This pull request aim to solve the issue of openSUSE Tumbleweed-Slowroll not being recognisable as an os.
[openSUSE Tumbleweed-Slowroll ](https://github.com/CISOfy/lynis/issues/1517)
> Adds openSUSE Tumbleweed-Slowroll to the list of recognisable os

- db/software-eol.db
This PR adds Rocky Linux version 8, 9 and 10 to the EOL DB. 
Information gathered from https://wiki.rockylinux.org/rocky/version/
> Add Rocky Linux to EOL DB

- include/tests_logging
Previously the text of the report would suggest a warning but report it as a suggestions. This was an inconsistency in the reporting as a warning was displayed in the report, but the summary showed
Great, no warnings
in case no other warning was reported.
> Report a warning if no logrotate configuration is found
