README.md

Minor textual tweak. :) The First Run section contains a list of instructions, but it wasn't displayed as a list.

Changed list of instructions to an actual list

---

include/tests_firewalls

Add test for 'ipfw' firewall on FreeBSD.

---

include/tests_authentication

Initial test to login failed login attempts via login.defs configuration.

Wrote 'AUTH-9407' - logging failed login attempts.

---

include/tests_tooling

Detect CFEngine3 presence, leaving earlier (cfengine2?) code in place
You can use my name in the contributions: Alexander Lobodzinski, Berlin, Germany

Tooling cf3

---

include/report

Calculate hardening index even in quiet mode

In quiet mode, hardening index was not written to log and report files

---

include/tests_storage

This module is a dependency of firewire-ohci as described in https://ieee1394.wiki.kernel.org/index.php/Juju_Migration

Added firewire-core module detection

---

include/tests_storage

Test [STRG-1840] checks authorization.

Implemented ISSUE: #11

---

include/tests_accounting
include/tests_printers_spools

[PRNT-2302]: Description text was obviously wrong

[PRNT-2302]: Description text was obviously wrong

---

include/tests_file_integrity

Added osqueryd as FIM

---

include/data_upload

Resolves below error:
./lynis: 25: ./include/data_upload: Syntax error: ";" unexpected

Removed errant semicolon which broke uploads

---

include/tests_nameservices

Case-insensitive searching for hostname.

Make NAME-4404 case-insensitive

---

include/tests_ports_packages

@mboelen what do you think of this as a first step to addressing issue #122 ?

Accept apt-get as a package audit tool

---

include/tests_ports_packages

Adds new test to detect Brew package manager and query installed packages.

Added brew as package manager.

---

include/tests_filesystems

Echo used instead of cat

---

include/tests_databases

The check if performing by doing a grep on db2sysc, the DB2 instance process.

Checks if DB2 LUW is running on a server

---

lynis

* replace too many `echo`s with `printf` to keep the code **DRY**
* `echo` is useful when it comes to printing the value of a variable or a (simple) line
* `printf` can basically do what the C version of it can do

Replace repetitive echo commands with single printf statement

---

include/tests_tooling

Oops!  Manual testing worked fine, but it failed under a cron job.
Also addressed #166

Replaced call to iptables with $IPTABLESBINARY

---

include/tests_ssh

Added section to log & display skipped atomic tests.

Display skipped atomic tests

---

include/tests_kernel

Minor reword ("latest" -> "latest installed")

---

include/tests_memory_processes

Attempt number two, fixing the awk line this time  :)

Remove wchan from PROC-3614, to finish #179

---

include/tests_filesystems

At line 431, you should maybe add some tests...

The XFS root FS is not checked

---

include/tests_filesystems

Check of /dev/shm:nosuid,nodev,noexec

---

include/tests_filesystems

Check if mount option is part of options, instead of just checking one value.

FILE-6372 : error in awk comparison

---

include/tests_filesystems

Check if a bind mount is done between /var/tmp and the directory /tmp

FILE-xyzz : Bind mount the /var/tmp directory to /tmp

---

include/tests_kernel

Use detected lsmod binary instead of calling it directly.

use ${LSMODBINARY} instead of lsmod

---

lynis

This is a solution for this issue: #213 
I just tested under CentOS 7.2

Fix: Automatic language detection

---

include/tests_time

There was a little typo in the test

Make time test 3106 work again

---

include/tests_logging

Filter out open+deleted files held by MySQL <5.6

---

include/functions

This made Lynis' last message show up even in --cronjob -q mode (instead of the tooltip).  Pretty confusing...

Fixed cut-and-paste error

---

include/tests_time

Update tests_time typo

---

default.prf
include/profiles

Added “personal” machine-role, changed “desktop” to “workstation”.

Updated profiles

---

include/tests_networking

Added support for DHCPD (related to issue #264)

NETW-3030 - DHCPD Support Added

---

include/functions
include/tests_authentication
include/tests_boot_services
include/tests_filesystems
include/tests_kernel

I wasn't sure how you go about choosing numbers, so I picked the next one up from the highest in a file and just checked to see if it existed anywhere else. I didn't update the changelog, as some people don't like that, but if you'd like I'll mention the work there. I also didn't add myself to contributors, but I was hoping to be added.

Improve DragonFly support

---

include/binaries
include/tests_mac_frameworks

This is looked up with the ```gradm``` tool.

Set MAC_FRAMEWORK_ACTIVE=1 if grsecurity's RBAC is enabled

---

include/tests_mail_messaging

Check if Linux version is set before using it in Postfix test

MAIL-8818: $LINUX_VERSION is not set on every OS

---

include/tests_authentication

This is an amended cherry-pick from #347.

Correct sulogin search pattern. Fix #345.

---

include/tests_php

Add a path to check for php.ini file

Add /usr/local/etc/zend/php.ini as possible php path

---

extras/build-lynis.sh
include/functions
include/osdetection
include/tests_authentication
include/tests_boot_services
include/tests_file_integrity
include/tests_firewalls
include/tests_kernel
include/tests_mac_frameworks
include/tests_networking
include/tests_ports_packages
include/tests_printers_spools
include/tests_squid
include/tests_ssh
lynis
plugins/plugin_pam_phase1

Documentation fix for the SafePerms function.
And then, a zillion whitespace fixes for indentation in if/fi blocks; see the specific commit message.
Then a couple of small typo/syntax error fixes.

Lots of cleanups

---

include/functions
include/helper_show
include/helper_system_remote_scan
include/helper_update
include/osdetection
include/tests_authentication
include/tests_kernel
include/tests_nameservices
include/tests_ports_packages
include/tests_scheduling
include/tests_shells
include/tests_tooling
lynis

I found that I still had a few problems in or like those listed in https://github.com/CISOfy/lynis/issues/214
With these changes, lynis runs without error for me on Solaris 10.
There may still be a few things that are sub-optimal on Solaris.

A bunch of Solaris compatibility tweaks

---

include/tests_php

removed php5.4,  added 7.0 and 7.1 and the flavours that are known on gentoo
(apache2, cgi, cli, embed,  fpm)

Added new php paths

---

include/helper_system_remote_scan

Added quote marks for the SSH commands in steps and 6.

Added quote marks on SSH commands

---

CONTRIBUTORS.md
include/tests_php

Add support for cPanel PHP (Scl-based pacakging) GHT #340

---

default.prf

Closes #386 
Add support for hardlink and symlink file protections.

Adds Protected Links Checks - Closes #386

---

include/tests_ports_packages

-F, --fetch
Fetch the database before checking.
[ci skip]

Fix pkg audit option

---

db/tests.db
include/tests_php

As you check for disabled functions within suhosin configuration I think this kind of test might be useful. I couldn't think in a better way in order to achieve it. what do you think ?

add suhosin status test

---

include/tests_php

I have added ini paths for cloudlinux

support for cloudlinux

---

include/tests_kernel
lynis

Fixes a couple of minor issues found while running on a minimal, non-PC system (Xilinx Zynq/busybox).

Minor fixes for embedded Linux.

---

include/tests_php

This PR will add enhancements to suhosin status check

Suhosin simulation mode status

---

db/tests.db
include/tests_firewalls

This PR will add two checks:
1. Check if CSF is running
2. Check APF (Advanced Policy Firewall) presence along with checking for testing mode status and check if its running

Firewall check updates

---

include/functions
include/tests_shells

Modified IsVirtualMachine() to :
- detect correctly LXC container in over-virtualization use case
- correct lscpu hypervisor detection
Added LXC detection code in IsContainer()

Enhanced detection for LXC and LXC over VM

---

include/tests_ssh

remove test for deprecated sshd option UsePrivilegeSeparation

---

include/osdetection
include/tests_ports_packages

The NetBSD packages vulnerabilities file is pkg-vulnerabilities.

[PKGS-7380] Fix NetBSD packages vulnerabilities file name

---

include/tests_crypto

Support spaces in file names

---

README.md

Minor issue but helpful in completing step-by-step usage.

README.md: added 'cd lynis' after git clone

---

README.md

Sorry, my bad. It broke the markdown formatting and in current state, it becomes unhelpful. Will be careful next time.

README.md: Fixed markdown formatting issue in my earlier contrib.

---

include/functions
include/tests_time

from man test:
-s FILE
FILE exists and has a size greater than zero
-z STRING
the length of STRING is zero

Check zero size of files correctly

---

include/tests_time

timedatectl status output was changed by the commit systemd/systemd@3ec530a

Fix detecting systemd timedate daemon

---

include/tests_php

resolves #420 also adds a warning if suhosin is enabled for PHP 7

lynis should not suggest suhosin for PHP 7

---

include/tests_filesystems

adresses this suggestion https://github.com/CISOfy/lynis/issues/435

[FILE-6363] Check for sticky bit on /var/tmp

---

FAQ
db/tests.db
extras/build-lynis.sh
include/functions
include/tests_logging
include/tests_squid
include/tests_time

Propose fix some typos

---

include/tests_php

Added php.ini paths used on Ubuntu with PHP 7.1/7.2

Update for PHP 7.2

---

include/helper_audit_dockerfile

also initialize a few variables which wasn't initialyzed

add alpine support

---

include/helper_audit_dockerfile

Missing quotes and better display

---

include/helper_audit_dockerfile

that's always better to specify the version, latest desn't mean latest version 
it can be a suggestion if you prefer

detect if latest TAG is used in dockerfile

---

include/helper_audit_dockerfile

Tiny contribution, but typos always catch my eye.

Typo fix in warning message

---

include/tests_shells

[SHLL-6230] Add etc/bash.bashrc.local to umask check

---

include/tests_authentication

This add support for RedHad and clones for tests [AUTH-9282] and [AUTH-9283].
This also fix issue #608 for these 2 tests.

[AUTH-9282][AUTH-9283] Add support for Red Hat and clones

---

include/tests_authentication

LDAP support for Red Hat and others (fix issue #612)

---

include/tests_filesystems

Add test FILE-6324 check XFS file systems

---

include/tests_insecure_services

Add tests INSE-8310 INSE-8312 (telnet)
Depend on #692

Add tests INSE-8310 INSE-8312 (telnet)

---

include/tests_filesystems

fix FILE-6374

---

include/tests_shells

Corrected SHLL-6220 test description

fix SHLL-6220 description

---

include/tests_authentication

Update AUTH-9402, change the uid name to check in etc/passwd file when device is a QNAP

Update tests_authentication - AUTH-9402

---

default.prf

Add some default permfile/permdir

Add some default permfile/permdir

---

include/tests_homedirs

fix issues #666 #667

---

include/tests_kernel

fix issue #659

---

CHANGELOG.md
include/helper_show
lynis.8

Add missing commands info to man and show helper

Improve help info with missing data

---

include/tests_usb

fix issue #610 STRG-1842

---

include/consts
include/functions

A few changes in order to strict mode to works.
So --profile developer.prf works again too.

strictmode fixes

---

include/functions
include/tests_file_permissions

Fix cut and grep so it works with permfile=

Changes for new profile format

---

include/functions

The important part was already fixed, this are warnings and info messages.
Closing #740 with this PR

Second version of #740 without shellcheck directives

---

include/tests_databases

fixes https://github.com/CISOfy/lynis/issues/783

Databases - variables initialization

---

include/tests_malware

New anti-virus detection for Kaspersky Labs

MALW-3280: Kaspersky detection

---

include/tests_homedirs

Closes #773
Patch taken from issue comments by @church1e
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cisofy/lynis/810)

Fix for false positive for some users on HOME-9306

---

include/osdetection

Adds raspbian as detectable OS in the osdetection module.

OS-Detection: add raspian detection

---

include/osdetection
include/parameters
lynis

colours and add macOS catalina

Soerelease

---

include/osdetection

Added detection of PureOS in /etc/os-release

---

db/tests.db
include/tests_boot_services

Detect rEFInd boot loader (https://www.rodsbooks.com/refind/).

Check for rEFInd boot loader

---

plugins/plugin_pam_phase1

pam: pam_selinux is known good module

---

db/tests.db
include/tests_crypto

Check for running audio-entropyd, havegd or jitterentropy-rngd.

Check for software pseudo random number generators

---

db/tests.db
include/binaries
include/tests_authentication

Manual page crypt(5) gives recommendations for choosing password
hashing methods, so let's check if there are weakly encrypted
passwords in the system.

Check password hashing methods

---

db/tests.db
include/binaries
include/tests_file_integrity

Check for evmctl (Extended Verification Module) tool and system IMA (Integrity Measurement
Architecture) status.

Check IMA/EVM, dm-integrity and dm-verity statuses

---

include/tests_mac_frameworks

Count and log unconfined processes which have no AppArmor profile
applied.

Enhance AppArmor check

---

include/binaries
include/tests_mac_frameworks

Count and log unconfined processes, which are not using policy
profile 3.

Enhance TOMOYO Linux check

---

include/tests_filesystems

Report total numbers of unhardened filesystems.

[FILE-6374]: Summarize unhardened file system

---

README.md

Show downstream usage for various versions of Lynis.

README.md: add repology badge

---

include/binaries

Report also number of set-uid and set-gid binaries found.

Enhance binaries report

---

include/tests_filesystems

Test FILE-6394 for vm.swappiness.
Different LogText for the different levels.

Adding test FILE-6394

---

CONTRIBUTING.md
HAPPY_USERS.md
README.md

Minor edits

---

include/tests_php

Add PHP 7.4 Detection Paths

---

include/osdetection

add Void Linux

---

db/software-eol.db

Update EOL dates according to the rules set in #1006.

Update macOS EOL

---

include/osdetection

Add NixOS and IPFire

---

include/osdetection

Add EndeavourOS to osdetection.

---

include/osdetection

Added OS detection block for Garuda Linux.

1122: Add OS detection block for Garuda Linux

---

db/software-eol.db

Updated URL for Alpine release information.
Added Alpine release 3.13 EOL date

Update EOL and URL for Alpine

---

include/tests_boot_services

[BOOT-5104] Add service manager detection support for runit

---

lynis

Corrected missing break for issue #1144

---

db/tests.db
include/tests_boot_services

Add TestID for ELILO
Add test for ELILO boot loader

New test: BOOT-5140 - Check for ELILO boot loader presence

---

include/osdetection

Automatic detection of Rocky Linux:
[+] Initializing program
------------------------------------
- Detecting OS...                                           [ DONE ]
- Checking profiles...                                      [ DONE ]
---------------------------------------------------
Program version:           3.0.4
Operating system:          Linux
Operating system name:     Rocky Linux
Operating system version:  8.3
Kernel version:            5.12.2
Hardware platform:         x86_64
Hostname:                  r83

Added detection of Rocky Linux to include/osdetection

---

include/tests_databases

Add mariadb as binary to check.

Update tests_databases for mariadb binary

---

include/tests_networking

grep options change from gnu to posix

---

include/osdetection

This pull request raised to close #1201 issue.

Added Funtoo Linux to osdetection

---

include/tests_kernel

Creating this file was introduced in [slackpkg](https://slackpkg.org/) version 15.0.10.

KRNL-5830: Check for /var/run/needs_restarting

---

include/functions

This PR:
- adds symlink support to HasCorrectFilePermissions and IsWorldWritable
- closes #1214 
- closes #1245 

add symlink support to HasCorrectFilePermissions and IsWorldWritable

---

include/tests_webservers

Update ModSecurity version. Actual version: 3
Issue #1246

Update mod_security module version

---

include/osdetection

This should close issue #1393. It does need to be tested since I don't have access to LSDK.

Update osdetection with LSDK

---

include/osdetection

This should close issue #1379.

Adding Guix to detected OSes

---

db/tests.db
include/tests_file_integrity
include/tests_hardening
include/tests_tooling

Adding tests for Wazuh: TOOL-5128 and FINT-4344
- Tested in Linux Debian.
- Closes #1319

Added tests considering Wazuh for file integrity and tooling

---

software-eol.db

EOL dates for current and obsolete versions of AIX.

AIX EOL updates

---

include/tests_webservers

Added the HTTP-6660 test  - test for TraceEnable setting in Apache.

Adding HTTP-6660 test

---

include/tests_banners

([Source](https://xkcd.com/838/))

Added "prosecute" & "report" to LEGAL_BANNER_STRINGS

---

include/osdetection

Add nobara osdetection

---

include/tests_ports_packages

This allows lynis enterprise to render the software  packages in the webinterface.

PKGS-7303: Added version numbers to brew packages.

---

include/tests_nameservices

- This PR closes #1280 
- Spent sometime trying to get ypbind up and running but couldn't. So this is not tested.

Adding missing test number for suggestion. Issue 1280

---

include/tests_filesystems

Added FILE-6398 (JBD driver loaded?) test

Added FILE-6398 test

---

include/osdetection

add "Koozali SME Server" in available distributions list.

osdetection: add Koozali #1274

---

include/tests_ports_packages

Query macOS /Applications and Apple CoreServices (Name & Version) and add them to the Report.

Added PKGS-7305 - macOS Applications and CoreService (Name & Version)

---

include/osdetection

This is a duplicate of #1310 with a live head.

Support Arch Linux ARM detection

---

include/tests_filesystems
include/tests_networking

Fix for issue https://github.com/CISOfy/lynis/issues/1502.

Fix REGEX for NETW-3200 and FILE-6430

---

README.md

Latest archive.org backup that I have found.

Article mirror - Update README.md

---

CHANGELOG.md
include/osdetection

add Buildroot

---

include/tests_firewalls

Include #1554
Fix FIND variable (remove **"\n"** and **-z**)
Add sort + uniq while read line from FIND

Update tests_firewalls -> FIRE-4508

---

include/osdetection

add gardenlinux  in osdetection

---

CHANGELOG.md
include/tests_firewalls

Hello, this PR fixes the FIRE-4508 control and adds  the following features:
- Deep parsing of `iptables` output with no dependencies.
- If the `sort` binary is present, the output includes only unique records; otherwise, it includes the raw results.
- Control if `NFQUEUE` target is present only in the security and filter tables.
iptables:
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -j NFQUEUE --queue-num 0 --queue-bypass
-A INPUT -j NFQUEUE --queue-num 1 --queue-bypass
```
Results:
```
[+] Software: firewalls
------------------------------------
- Checking iptables kernel module                           [ FOUND ]
- Checking iptables policies of chains                    [ FOUND ]
- Checking chain INPUT (table: filter, target: ACCEPT)  [ ACCEPT ]
- Checking chain …
```

FIRE-4508 - Enhancements

---

include/tests_boot_services

Fix for issue https://github.com/CISOfy/lynis/issues/1566.

Fix for issue #1566.

---

include/tests_malware

Detect if Bitdefender is running on Linux.

Bitdefender daemon on Linux is called bdsecd

---

include/osdetection

This adds the latest macOS release releasing in the fall of 2025.

Add macOS Tahoe

---

include/osdetection

Added CachyOS to include/osdetection

Update osdetection - added CachyOS
